father(Alexander Zhivalev, Egor Zhivalev).
father(Vladimir Artemyev, Alla Artemyeva).
father(Vladimir Artemyev, Igor Artemyev).
father(Vasily Zhivalev, Alexander Zhivalev).
father(Vasily Zhivalev, Lena Zhivaleva).
father(Igor Artemyev, Vladimir Artemyev).
father(Igor Artemyev, Alexey Artemyev).
father(Igor Artemyev, Valeria Artemyeva).
father(Igor Artemyev, Alena Artemyeva).
father(Igor Artemyev, Julia Artemyeva).
father(Alexander Chashinov, Alevtina Artemyeva).
father(Alexander Chashinov, Tatyana Solovyeva).
father(Vladimir Solovyev, Alexander Solovyev).
father(Vladimir Solovyev, Denis Solovyev).
father(Alexander Solovyev, Konstantin Solovyev).
father(Denis Solovyev, Artem Solovyev).
father(Denis Solovyev, Alexandra Solovyeva).
father(Alexander Artemyev, Vladimir Artemyev).
father(Alexander Artemyev, Ludmila Artemyeva).
father(Evgeny Romanov, Tatyana Romanova).
father(Yuri Panshin, Irina Panshina).

mother(Alla Artemyeva, Egor Zhivalev).
mother(Alevtina Artemyeva, Alla Artemyeva).
mother(Alevtina Artemyeva, Igor Artemyev).
mother(Maria Zhivaleva, Alexander Zhivalev).
mother(Maria Zhivaleva, Lena Zhivaleva).
mother(Irina Perovksaya, Vladimir Artemyev).
mother(Irina Perovksaya, Alexey Artemyev).
mother(Irina Perovksaya, Valeria Artemyeva).
mother(Irina Perovksaya, Alena Artemyeva).
mother(Irina Perovksaya, Julia Artemyeva).
mother(Tatyana Solovyeva, Alexander Solovyev).
mother(Tatyana Solovyeva, Denis Solovyev).
mother(Natalya Solovyeva, Konstantin Solovyev).
mother(Natalya Solovyeva, Artem Solovyev).
mother(Natalya Solovyeva, Alexandra Solovyeva).
mother(Ludmila Artemyeva, Evgeny Romanov).
mother(Ludmila Artemyeva, Julia Kosolapova).
mother(Julia Kosolapova, Vladislav Kosolapov).
mother(Lena Zhivaleva, Irina Panshina).
